### ISSUE TITLE
[BUG/Question] when item is rotated, left & top is calculated incorrectly

### ISSUE THREAD

**Issue by ctf0** [daybrush/moveable#254] opened 2020-06-03 16:50 UTC
## Environments
* Framework name: vanilla
* Framework version: latest
* Moveable Component version:
* Testable Address(optional):

## Description

am not really sure if this is intended or is a bug but when item is rotated, the left/top should be the same as the normal

- rotated
![remo](https://user-images.githubusercontent.com/7388088/83662891-6c76f900-a5c8-11ea-9d12-2f4750ba971e.gif)

- normal
![ScreenFlow](https://user-images.githubusercontent.com/7388088/83663122-b65fdf00-a5c8-11ea-99cf-df940c620120.gif)

- code
```js
let rotate = 0
let movable = new Moveable(document.querySelector('product'), {
    target      : document.querySelector('logo'),
    dragArea    : true,
    draggable   : true,
    throttleDrag: 0,

    rotatable     : true,
    throttleRotate: 5,

    resizable     : true,
    throttleResize: 0,
    keepRatio     : true,
    baseDirection : [1, 1],

    pinchable     : true,
    pinchThreshold: 20,
    origin        : false,
    edge          : false,

    snappable         : true,
    snapThreshold     : 0,
    snapCenter        : true,
    isDisplaySnapDigit: false,
    elementGuidelines : [document.querySelector('shirt')],
    bounds            : {
                top   : 0,
                bottom: document.querySelector('shirt').clientHeight,
                left  : 0,
                right : document.querySelector('shirt').clientWidth
            }
    })

movable
    .on('drag', ({target, left, top}) => {
        target.style.left = left + 'px'
        target.style.top = top + 'px'
    })
    .on('resize', ({target, width, height, drag}) => {
        target.style.width  = width + 'px'
        target.style.height = height + 'px'
        target.style.left   = drag.left + 'px'
        target.style.top    = drag.top + 'px'
    })
    .on('rotate', ({target, delta}) => {
        let current = rotate + delta

        if (current > 180 || current < -180) {
            return false
        }

        target.style.transform = `rotate(${(Math.round(current))})deg`
    })
```

- demo https://jsfiddle.net/muah003/w2x9q04r/9/

**Comment by daybrush** [comment] 2020-06-03 18:48
@ctf0 

It's duplicate of #235 . Thank you :)

I'll fix it.

**Comment by ctf0** [comment] 2020-06-03 19:48
oh okay, thanx for the headsup

**Comment by daybrush** [comment] 2020-06-04 02:20
@ctf0 
Since this is 50% to 50% transform-origin, I think it might be different.

**Comment by ctf0** [comment] 2020-06-05 03:58
btw the movement is relative to the item size, ex if the movable box is small you can drag more to the left but as it gets bigger you become more limited as in the gif.

**Comment by daybrush** [comment] 2020-06-05 13:36
@ctf0 

uhmmm gif pictures and corresponding comment look like a normal behavior?

**Comment by ctf0** [comment] 2020-06-05 14:46
not exactly, the main issue meant to show that the left/top gives incorrect values of negative numbers, where it should be `0` like the normal unrotated box.

the prev comment meant for usage of
```
.on('drag', ({target, left, top}) => {
        target.style.left = left < 0 ? 0 : left + 'px'
        target.style.top = top < 0 ? 0 : top + 'px'
    })
```

try with this logic and u will see what i mean.

**Comment by ctf0** [comment] 2020-06-06 12:19
i think i know the issue, when the item is rotated, the width & height calculation should be changed but i found when using `clientWidth` u will get the first render width no mater what u do. maybe thats what moveable is using ?

**Comment by daybrush** [comment] 2020-06-08 01:58
@ctf0 

Moveable bounds are judged by each point, not by left and top.

**Comment by ctf0** [comment] 2020-06-08 02:50
u r missing the point, i meant the reason behind the negative values for top & left is because of the width calculation that doesnt change when u rotate the box.

**Comment by ctf0** [comment] 2020-08-29 15:50
any updates ?, if you want my help with something just ask 🥇

**Comment by EffakT** [comment] 2020-11-22 19:34
If I understand your issue, it is similar to mine.
One thought I had, would be seeing if it is possible to calculate the location of the element from the centre of the element, instead of the top-left?

**Comment by daybrush** [comment] 2020-12-01 17:05
@ctf0 

if you rotate as you said, the widsth and height calculations are a little different.

However left 0 and top 0 of bounds are clientRect.

it does not mean left or top of css style, it can be negative.

**Comment by ctf0** [comment] 2020-12-01 18:02
@daybrush sorry i dont understand what u mean.

maybe am wrong but am very sure that if u moved a box to the corner which is `0,0` no matter how u rotate the box it should always be `0,0` not `-20,0`

**Comment by daybrush** [comment] 2020-12-02 02:00
Whenever rotation is finished, set the bounds like this.
Moveable doesn't support your method. However, you can create a method by setting bounds arbitrarily.

```js
    const containerRect = shirt.getBoundingClientRect();
    const itemRect = logo.getBoundingClientRect();
    const itemStyle = window.getComputedStyle(logo);

    const left = itemRect.left - containerRect.left - parseFloat(itemStyle.left);
    const top = itemRect.top - containerRect.top - parseFloat(itemStyle.top);
```

**Comment by ctf0** [comment] 2020-12-02 20:31
perfect, many thanx, getting there.

btw `window.getComputedStyle(logo)` is not needed.

now is there a way to make sure the logo is moved all the way to left so it becomes `0,0` ?

**Closed** 2023-11-17 11:06 UTC
Labels: bug, question
