### ISSUE TITLE
[BUG] resize could go outside the configured boundaries

### ISSUE THREAD

**Issue by ctf0** [daybrush/moveable#253] opened 2020-06-03 14:58 UTC
## Environments
* Framework name: vanilla
* Framework version: latest
* Moveable Component version:
* Testable Address(optional):

## Description
- with rotation it may cuz flickering
![demo](https://user-images.githubusercontent.com/7388088/83652079-7eea3600-a5ba-11ea-8740-cabe57994406.gif)

- without rotation
![demo 2](https://user-images.githubusercontent.com/7388088/83651983-624dfe00-a5ba-11ea-9875-5edd6a169360.gif)

- and here is the code
```js
let rotate = 0
let movable = new Moveable(document.querySelector('product'), {
    target      : document.querySelector('logo'),
    dragArea    : true,
    draggable   : true,
    throttleDrag: 0,

    rotatable     : true,
    throttleRotate: 5,

    resizable     : true,
    throttleResize: 0,
    keepRatio     : true,
    baseDirection : [1, 1],

    pinchable     : true,
    pinchThreshold: 20,
    origin        : false,
    edge          : false,

    snappable         : true,
    snapThreshold     : 0,
    snapCenter        : true,
    isDisplaySnapDigit: false,
    elementGuidelines : [document.querySelector('shirt')],
    bounds            : {
                top   : 0,
                bottom: document.querySelector('shirt').clientHeight,
                left  : 0,
                right : document.querySelector('shirt').clientWidth
            }
    })

movable
    .on('drag', ({target, left, top}) => {
        target.style.left = left < 0 ? 0 : left + 'px'
        target.style.top = top < 0 ? 0 : top + 'px'
    })
    .on('resize', ({target, width, height, drag}) => {
        target.style.width  = width + 'px'
        target.style.height = height + 'px'
        target.style.left   = drag.left + 'px'
        target.style.top    = drag.top + 'px'
    })
    .on('rotate', ({target, delta}) => {
        let current = rotate + delta

        if (current > 180 || current < -180) {
            return false
        }

        target.style.transform = `rotate(${(Math.round(current))})deg`
    })
```

**Comment by ctf0** [comment] 2020-06-03 19:48
@daybrush can u plz elaborate ?!!

**Comment by daybrush** [comment] 2020-06-04 02:20
@ctf0 

Oh. Sorry.

I am confused with the issue below.
https://github.com/daybrush/moveable/issues/254

It's duplicate of #235 .

**Comment by daybrush** [comment] 2020-06-04 19:14
@ctf0  

* `moveable` 0.17.9
* `react-moveable` 0.20.9
* `preact-moveable` 0.19.9
* `ngx-moveable` 0.13.10
* `svelte-moveable` 0.8.10

moveable's new version is released. Check it again.

**Comment by ctf0** [comment] 2020-06-04 23:14
nothing changed unfortunately 😢

**Comment by ctf0** [comment] 2020-06-04 23:14
nothing new, issue still persist

**Comment by daybrush** [comment] 2020-06-05 02:29
@ctf0 

I'm not sure why?

Add this code:
```js
.on("resizeStart", ({ setOrigin }) => {
    setOrigin(["%", "%"]);
})
```

If not, wouldn't you give me a test address?

**Comment by ctf0** [comment] 2020-06-05 03:53
still nothing, i will prepare a demo and add it today, thank you for ur help.

**Comment by ctf0** [comment] 2020-06-05 10:41
https://jsfiddle.net/muah003/w2x9q04r/4/

**Comment by daybrush** [comment] 2020-06-07 17:57
@ctf0 

* `moveable` 0.17.10
* `react-moveable` 0.20.10
* `preact-moveable` 0.19.10
* `ngx-moveable` 0.13.11
* `svelte-moveable` 0.8.11

moveable's new version is released.

**Comment by ctf0** [comment] 2020-06-07 18:59
awesome, much appreciated.

btw is there a way to stop the resize once the boundaries are meet instead of the current ? as it flickers a little bit which kinda looks like the box is struggling to whether to resize or not.

**Comment by daybrush** [comment] 2020-06-08 01:59
@ctf0 

How about using max-width or max-height?

**Comment by ctf0** [comment] 2020-06-08 02:50
oh okay, will give it a go, thanx for the headsup

**Closed** 2020-06-09 18:03 UTC
Labels: complete, question
