### ISSUE TITLE
Possible to convert snappable units before display

### ISSUE THREAD

**Issue by modemmute** [daybrush/moveable#229] opened 2020-05-01 20:39 UTC
Feature Request:

I'm allowing users to utilize different measurement units on my site (inch, centimeter, pixel, etc). The snappable guides appear to only report distances in pixels on the screen. Is it possible to support converting those numbers into different units before they're displayed?

Many thanks for this fantastic library!

**Comment by daybrush** [comment] 2020-05-02 02:27
@modemmute 

Thank you :) it's duplicate of #209

**Comment by daybrush** [comment] 2020-05-02 18:08
@modemmute  

moveable's new version is released.

* `moveable` 0.17.1
* `react-moveable` 0.20.1
* `preact-moveable` 0.19.1
* `ngx-moveable` 0.13.1
* `svelte-moveable` 0.8.1

add `snapDistFormat` props.

https://daybrush.com/moveable/release/latest/doc/Moveable.html#snapDistFormat

**Closed** 2020-07-07 19:29 UTC
Labels: Feature, complete
