### ISSUE TITLE
Resizing breaks if using keepRatio + snapping + rotation 90 or 270 degrees

### ISSUE THREAD

**Issue by miina** [daybrush/moveable#251] opened 2020-06-03 13:12 UTC
## Environments
* Framework name: React
* Framework version: 16.13.1
* Moveable Component version: 0.20.8
* Testable Address(optional): https://codesandbox.io/s/react-moveable-resizing-djzcr

## Description

Moveable seems to be breaking when some certain conditions, that is when:
1. `keepRatio` is set to `true`.
2. `canSnap` is set to `true` and the element is in the edge of a snapping point.
3. The element is rotated 90 or 270 degrees.

See demo:
![resizing](https://user-images.githubusercontent.com/3294597/83640353-4cd1d780-a5ac-11ea-8728-1d23d61d8a1d.gif)

**Comment by daybrush** [comment] 2020-06-03 13:13
@miina 

It's duplicate of #235 
I'll fix it. Thank you :)

**Comment by miina** [comment] 2020-06-03 13:17
Oh, didn't realize there was a duplicate, thank you!

**Closed** 2020-06-03 13:18 UTC
Labels: bug

**Comment by daybrush** [comment] 2020-06-04 19:13
@miina 

* `moveable` 0.17.9
* `react-moveable` 0.20.9
* `preact-moveable` 0.19.9
* `ngx-moveable` 0.13.10
* `svelte-moveable` 0.8.10

moveable's new version is released. Check it again.

**Comment by miina** [comment] 2020-06-04 19:31
Seems to work as expected now, thank you!
